# Generated by Django 5.2.1 on 2025-06-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('summary', models.TextField()),
                ('room_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('doctor_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('medicine_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
    ]
