# Generated by Django 5.2.1 on 2025-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_doctor_contact_number_remove_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
