# Generated by Django 4.2.27 on 2026-02-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0013_alter_emaillog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                max_length=10,
            ),
        ),
    ]
